language: erlang

sudo: required
dist: xenial

otp_release:
    - 21.0

env:
    - ELIXIR_VERSION=1.6.6-otp-21
    - ELIXIR_VERSION=1.7.3-otp-21

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libmnl-dev
    - wget https://repo.hex.pm/builds/elixir/v$ELIXIR_VERSION.zip
    - unzip -d elixir v$ELIXIR_VERSION.zip

before_script:
    - export PATH=`pwd`/elixir/bin:$PATH

script:
    - mix local.hex --force
    - mix deps.get
    - mix test
    - if (elixir -v | grep 1.7); then mix docs; mix format --check-formatted; fi
    - mix hex.build
