language: erlang

sudo: required
dist: trusty

otp_release:
    - 19.2

env:
    - ELIXIR_VERSION=1.4.5

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libmnl-dev
    - wget https://github.com/elixir-lang/elixir/releases/download/v$ELIXIR_VERSION/Precompiled.zip
    - unzip -d elixir Precompiled.zip

before_script:
    - export PATH=`pwd`/elixir/bin:$PATH

script:
    - mix local.hex --force
    - mix deps.get
    - mix test
